/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as CollectionIdRouteImport } from './routes/collection.$id'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedGuidesNewRouteImport } from './routes/_authenticated/guides.new'
import { Route as AuthenticatedCollectionsNewRouteImport } from './routes/_authenticated/collections.new'
import { Route as AuthenticatedGuidesIdEditRouteImport } from './routes/_authenticated/guides.$id.edit'
import { Route as AuthenticatedCollectionsIdEditRouteImport } from './routes/_authenticated/collections.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIdRoute = CollectionIdRouteImport.update({
  id: '/collection/$id',
  path: '/collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGuidesNewRoute = AuthenticatedGuidesNewRouteImport.update({
  id: '/guides/new',
  path: '/guides/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsNewRoute =
  AuthenticatedCollectionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCollectionsRoute,
  } as any)
const AuthenticatedGuidesIdEditRoute =
  AuthenticatedGuidesIdEditRouteImport.update({
    id: '/guides/$id/edit',
    path: '/guides/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsIdEditRoute =
  AuthenticatedCollectionsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedCollectionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/collection/$id': typeof CollectionIdRoute
  '/g/$slug': typeof GSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/guides/new': typeof AuthenticatedGuidesNewRoute
  '/collections/$id/edit': typeof AuthenticatedCollectionsIdEditRoute
  '/guides/$id/edit': typeof AuthenticatedGuidesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/collection/$id': typeof CollectionIdRoute
  '/g/$slug': typeof GSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/guides/new': typeof AuthenticatedGuidesNewRoute
  '/collections/$id/edit': typeof AuthenticatedCollectionsIdEditRoute
  '/guides/$id/edit': typeof AuthenticatedGuidesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/collection/$id': typeof CollectionIdRoute
  '/g/$slug': typeof GSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/_authenticated/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/_authenticated/guides/new': typeof AuthenticatedGuidesNewRoute
  '/_authenticated/collections/$id/edit': typeof AuthenticatedCollectionsIdEditRoute
  '/_authenticated/guides/$id/edit': typeof AuthenticatedGuidesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/collections'
    | '/dashboard'
    | '/settings'
    | '/collection/$id'
    | '/g/$slug'
    | '/profile/$username'
    | '/collections/new'
    | '/guides/new'
    | '/collections/$id/edit'
    | '/guides/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/collections'
    | '/dashboard'
    | '/settings'
    | '/collection/$id'
    | '/g/$slug'
    | '/profile/$username'
    | '/collections/new'
    | '/guides/new'
    | '/collections/$id/edit'
    | '/guides/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_authenticated/collections'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/collection/$id'
    | '/g/$slug'
    | '/profile/$username'
    | '/_authenticated/collections/new'
    | '/_authenticated/guides/new'
    | '/_authenticated/collections/$id/edit'
    | '/_authenticated/guides/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  CollectionIdRoute: typeof CollectionIdRoute
  GSlugRoute: typeof GSlugRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$id': {
      id: '/collection/$id'
      path: '/collection/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof CollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guides/new': {
      id: '/_authenticated/guides/new'
      path: '/guides/new'
      fullPath: '/guides/new'
      preLoaderRoute: typeof AuthenticatedGuidesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/new': {
      id: '/_authenticated/collections/new'
      path: '/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof AuthenticatedCollectionsNewRouteImport
      parentRoute: typeof AuthenticatedCollectionsRoute
    }
    '/_authenticated/guides/$id/edit': {
      id: '/_authenticated/guides/$id/edit'
      path: '/guides/$id/edit'
      fullPath: '/guides/$id/edit'
      preLoaderRoute: typeof AuthenticatedGuidesIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$id/edit': {
      id: '/_authenticated/collections/$id/edit'
      path: '/$id/edit'
      fullPath: '/collections/$id/edit'
      preLoaderRoute: typeof AuthenticatedCollectionsIdEditRouteImport
      parentRoute: typeof AuthenticatedCollectionsRoute
    }
  }
}

interface AuthenticatedCollectionsRouteChildren {
  AuthenticatedCollectionsNewRoute: typeof AuthenticatedCollectionsNewRoute
  AuthenticatedCollectionsIdEditRoute: typeof AuthenticatedCollectionsIdEditRoute
}

const AuthenticatedCollectionsRouteChildren: AuthenticatedCollectionsRouteChildren =
  {
    AuthenticatedCollectionsNewRoute: AuthenticatedCollectionsNewRoute,
    AuthenticatedCollectionsIdEditRoute: AuthenticatedCollectionsIdEditRoute,
  }

const AuthenticatedCollectionsRouteWithChildren =
  AuthenticatedCollectionsRoute._addFileChildren(
    AuthenticatedCollectionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedGuidesNewRoute: typeof AuthenticatedGuidesNewRoute
  AuthenticatedGuidesIdEditRoute: typeof AuthenticatedGuidesIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedGuidesNewRoute: AuthenticatedGuidesNewRoute,
  AuthenticatedGuidesIdEditRoute: AuthenticatedGuidesIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  CollectionIdRoute: CollectionIdRoute,
  GSlugRoute: GSlugRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
